#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          arm,           tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     mLeft,         tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     mRight,        tmotorNormal, openLoop, reversed, encoder)


//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "AutoCommon.c"

task main() {
  promptSide(); // Ask which side
  promptDelay();  // Ask how long to wait

  waitForStart(); // Wait for the round to begin
  wait1Msec(startDelay * 1000); // Wait the given delay

  turnRight(60, 1000);  // Turn right
  turnRight(-100, 1340);  // Turn left
}
