#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          arm,           tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     mLeft,         tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     mRight,        tmotorNormal, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#include "Common.c"

// Here's the robot specific code for controlling the arm
void robotSpecial() {
  motor[arm] = joy2y1();
}
