#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     touchsensor,    sensorTouch)
#pragma config(Motor,  mtr_S1_C2_1,     arm2,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     belt,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     leftFront,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     leftBack,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     arm1,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,      ,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     rightFront,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_2,     rightBack,     tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"

/*
* arm.c controls the robot's arm.  It is THE ONLY file that knows about the arms motors, sensors
* and other sub-cmpontets. arm.c provides functions such as raise, lower, and stop.
*
* TO-DOs
*   o When you accomplish a task below, change the first character from 'o' to 'x'
*   o Try reducing the nuber of pragmas above to only those required by the arm motors & sensors.
*/

/*
void arm_lower()
{
	if (SensorValue(touchsensor) == 0)
	{
		motor [arm1] = 100;
		motor [arm2] = 100;
	}
	 else if (SensorValue(touchsensor) == 1)
	{
		motor [arm1] = 0;
		motor [arm2] = 0;

	}
}
void arm_raise()
{
	if (SensorValue(touchsensor) == 0)
	{
		motor [arm1] = -100;
		motor [arm2] = -100;
	}
	else if (SensorValue(touchsensor) == 1)
	{
		motor [arm1] = 0;
		motor [arm2] = 0;
	}
}
void arm_stop()
{
	motor [arm1] = 0;
	motor [arm2] = 0;
}
*/

void arm_move ()
{
	motor [arm1] = joystick.joy2_y2;
	motor [arm2] = joystick.joy2_y2;
}
