#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,      ,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,      ,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,      ,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,      ,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,      ,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,      ,             tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void latch1_open() //latch 1 unlocks
{
	servo [servo1] = 50;
	wait1Msec (1000);
}

void latch1_close() //latch 1 closes
{
	servo [servo1] = -50;
	wait1Msec (1000);
}

void latch2_open() //latch 2 opens
{
	servo [servo2] = 50;
	wait1Msec (1000);
}

void latch2_close() //latch 2 closes
{
	servo [servo2] = -50;
	wait1Msec (1000);
}
