#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorA,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
task main()
{
	while (true)
	{
		if (joystick.joy1_y1 > 30)
		{
			getJoystickSettings(joystick);
			motor[motorA] = joystick.joy1_y1;
		}
		if (joystick.joy1_y2 > 30)
		{
			getJoystickSettings(joystick);
			motor[motorE] = joystick.joy1_y2;
		}
	}
}
