#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S3,     touch1,         sensorTouch)
#pragma config(Sensor, S4,     touch2,         sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     motorA,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorB,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorC,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorD,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     armA,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     armB,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     collector,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorK,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)

/* Original Vex Pragmas
#pragma config(Motor,  port2,           frontRight,    tmotorNormal, openLoop)
#pragma config(Motor,  port3,           backRight,     tmotorNormal, openLoop)
#pragma config(Motor,  port4,           frontLeft,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port5,           backLeft,      tmotorNormal, openLoop, reversed)
*/

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Thise file orignally came from
C:\Program Files\Robomatter Inc\ROBOTC Development Environment 4.X\
Sample Programs\VEX2\Remote Control\Mecanum Drive - Basic.c

*/

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
Mecanum Drive - Basic
- This program allows you to remotely control a robot with mecanum wheels.
- The left joystick Y-axis controls the robot's forward and backward movement.
- The left joystick X-axis controls the robot's left and right movement.
- The right joystick X-axis controls the robot's rotation.

[I/O Port]          [Name]              [Type]                [Description]
Motor Port 2        frontRight          VEX Motor             Front Right motor
Motor Port 3        backRight           VEX Motor             Back Right motor
Motor Port 4        frontLeft           VEX Motor             Front Left motor
Motor Port 5        backLeft            VEX Motor             Back Left motor
----------------------------------------------------------------------------------------------------*/

#include "JoystickDriver.c"

task main()
{
	//Loop Forever
	while(1 == 1)
	{
		/* original Vex code
		//Remote Control Commands
		motor[frontRight] = vexRT[Ch3] - vexRT[Ch1] - vexRT[Ch4];
		motor[backRight] =  vexRT[Ch3] - vexRT[Ch1] + vexRT[Ch4];
		motor[frontLeft] = vexRT[Ch3] + vexRT[Ch1] + vexRT[Ch4];
		motor[backLeft] =  vexRT[Ch3] + vexRT[Ch1] - vexRT[Ch4];
		*/

		/*
		The wierd VexRT varaibles are the way Vex talks to its joystick.

		Vex runs off of the kind of radio transmitter you'd use to fly an
		RC Plane.  One big box, with two joysticks, operated by your thumbs.
		Below is a mapping from these vexRT vars to an FTC game controlller

		Vex variable          Meaning             FTC controller
		------------    ----------------------    ----------------
		vexRT[Ch3]   == left  joystick, y-axis == joystick.joy1_y1
		vexRT[Ch4]   == left  joystick, x-axis == joystick.joy1_x1
		vexRT[Ch1]   == right joystick, x-axis == joystick.joy1_x2
		*/

		// Modified code, for FTC
		// Not sure if the front motors are A and B, or C and D.
		motor[motorB] = joystick.joy1_y1 - joystick.joy1_x2 - joystick.joy1_x1;
		motor[motorD] = joystick.joy1_y1 - joystick.joy1_x2 + joystick.joy1_x1;
		motor[motorA] = joystick.joy1_y1 + joystick.joy1_x2 + joystick.joy1_x1;
		motor[motorC] = joystick.joy1_y1 + joystick.joy1_x2 - joystick.joy1_x1;

		// if the code above makes the robot go backwards, comment it out, and
		// uncomment the code belo by deleting the /* and the */

		/*
		motor[motorD] = joystick.joy1_y1 - joystick.joy1_x2 - joystick.joy1_x1;
		motor[motorG] = joystick.joy1_y1 - joystick.joy1_x2 + joystick.joy1_x1;
		motor[motorC] = joystick.joy1_y1 + joystick.joy1_x2 + joystick.joy1_x1;
		motor[motorA] = joystick.joy1_y1 + joystick.joy1_x2 - joystick.joy1_x1;
		*/
	}
}
