#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorA,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorB,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorC,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorD,        tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "drivebase.c"
task main()
{
	while (true)
	{
		getJoystickSettings(joystick);

		if (joy1Btn(2) == 0)
		{
			tankdrive (joystick.joy1_y1 / 5, joystick.joy1_y2 / 5);
		}
		if (joy1Btn(2) == 1)
		{
			translatedrive (joystick.joy1_x1 / 5);
		}
	}


}
