#pragma config(Motor,  motorA,          Left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          Right,         tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	motor[motorA] = 75;
	motor[motorB] = 75;
	wait1Msec (3000);

	motor[motorA] = -75;
	motor[motorB] = -75;
	wait1Msec (2000);

	motor [motorA] = 50;
	motor [motorB] = 25;
	wait1Msec (4000);

	motor [motorA] = 10;
	motor [motorB] = 60;
	wait1Msec (3000);

}
