#pragma config(Sensor, S1,     TouchLeft,      sensorTouch)
#pragma config(Sensor, S2,     TouchRight,     sensorTouch)
#pragma config(Sensor, S3,     TouchFore,      sensorTouch)
#pragma config(Motor,  motorA,          LeftMotor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          RightMotor,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool RightPressed;
bool LeftPressed;
bool ForePressed;
task main()

{
	while (true)
	{
		RightPressed = SensorBoolean (TouchLeft);
		LeftPressed = SensorBoolean (TouchRight);
		ForePressed = SensorBoolean (TouchFore);



		//	if ((RightPressed) && (!ForePressed))
		//	{
		//		motor [RightMotor] = 75;
		//	}
		//	else
		//		{
		//			motor [RightMotor] = 0;
		//
		//		}
		//	if ((LeftPressed) && (!ForePressed))
		//	{
		//		motor [LeftMotor] = 75;
		//		else
		//		{
		//			motor [LeftMotor] = 0;
		//
		//	}
		//	if (ForePressed)
		//		{
		//
		//			motor [LeftMotor] = -75;
		//
		//
		//			motor [RightMotor] = -75;
		//		}
		//		else
		//			motor [LeftMotor] = 0;
		//			motor [RightMotor] = 0;

		//		}

		//	}

		if (RightPressed)
		{
			motor [RightMotor] = 75;

		}
		else if (LeftPressed)
		{
			motor [LeftMotor] = 75;
		}
		else if (ForePressed)
		{
			motor [LeftMotor] = -75;
			motor [RightMotor] = -75;

		}
		else
		{
			motor [LeftMotor] = 0;
			motor [RightMotor] = 0;
	}
}
}
